# Generated by Django 5.0.1 on 2024-01-10 09:49

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hostel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostel_name", models.CharField(max_length=255)),
                (
                    "hostel_type",
                    models.CharField(
                        choices=[("Boys", "Boys"), ("Girls", "Girls")], max_length=10
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("number_of_floors", models.PositiveIntegerField()),
                ("number_of_rooms", models.PositiveIntegerField()),
                (
                    "type_of_room",
                    models.CharField(
                        choices=[("Single", "Single"), ("Double", "Double")],
                        max_length=10,
                    ),
                ),
                ("warden_assigned", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="HostelFees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rent", models.DecimalField(decimal_places=2, max_digits=10)),
                ("food", models.DecimalField(decimal_places=2, max_digits=10)),
                ("transport", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master_app.hostel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.IntegerField()),
                ("room_strength", models.IntegerField()),
                (
                    "room_assets",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("Air Conditioner", "Air Conditioner"),
                            ("Water Heater", "Water Heater"),
                            ("Bed", "Bed"),
                            ("Fridge", "Fridge"),
                            ("Stove", "Stove"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master_app.hostel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("register_number", models.CharField(max_length=30, unique=True)),
                ("gender", models.CharField(max_length=10)),
                ("date_of_birth", models.DateField()),
                ("contact_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("parents_number", models.CharField(max_length=15)),
                ("blood_group", models.CharField(max_length=5)),
                ("department", models.CharField(max_length=50)),
                ("check_in_date", models.DateField()),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostelstudent",
                        to="master_app.hostel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("student_name", models.CharField(max_length=100)),
                ("contact_number", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                (
                    "child",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master_app.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Warden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("register_number", models.CharField(max_length=20)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("qualification", models.CharField(max_length=255)),
                ("contact_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                (
                    "hostel_assigned",
                    models.CharField(default="Hostel_Name", max_length=100),
                ),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warden",
                        to="master_app.hostel",
                    ),
                ),
            ],
        ),
    ]
