# Generated by Django 5.0.1 on 2024-01-10 10:39

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hostel",
            name="type_of_room",
        ),
        migrations.RemoveField(
            model_name="room",
            name="room_strength",
        ),
        migrations.AddField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("Single", ""),
                    ("Two share", "Water Heater"),
                    ("Three share", "Fridge"),
                    ("Four share", "Stove"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="room",
            name="room_assets",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Air Conditioner", "Air Conditioner"),
                    ("Water Heater", "Water Heater"),
                    ("Fridge", "Fridge"),
                    ("Stove", "Stove"),
                ],
                max_length=100,
            ),
        ),
    ]
