# Generated by Django 5.0.1 on 2024-01-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "master_app",
            "0002_remove_hostel_type_of_room_remove_room_room_strength_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_assets",
            field=models.CharField(
                choices=[
                    ("Air Conditioner", "Air Conditioner"),
                    ("Water Heater", "Water Heater"),
                    ("Fridge", "Fridge"),
                    ("Stove", "Stove"),
                ],
                max_length=100,
            ),
        ),
    ]
