# Generated by Django 5.0.1 on 2024-01-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_app", "0003_alter_room_room_assets"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="room_assets",
            field=models.CharField(
                choices=[
                    ("Air Conditioner", "Air Conditioner"),
                    ("Water Heater", "Water Heater"),
                    ("Fridge", "Fridge"),
                    ("Stove", "Stove"),
                ],
                default=1,
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="room_number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("Single", ""),
                    ("Two share", "Water Heater"),
                    ("Three share", "Fridge"),
                    ("Four share", "Stove"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
