# Generated by Django 5.0.1 on 2024-01-12 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_app", "0004_student_room_assets_student_room_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostelfees",
            name="hostel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="master_app.hostel"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="hostel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="hostelstudent",
                to="master_app.hostel",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("Single", "Single"),
                    ("Two share", "Two share"),
                    ("Three share", "Three share"),
                    ("Four share", "Four share"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="warden",
            name="hostel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="warden",
                to="master_app.hostel",
            ),
        ),
    ]
