# Generated by Django 5.0.1 on 2024-01-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_app", "0005_alter_hostelfees_hostel_alter_student_hostel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parent",
            name="contact_number",
            field=models.CharField(max_length=15),
        ),
    ]
