# Generated by Django 5.0.1 on 2024-01-17 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_app", "0006_alter_parent_contact_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="hostel",
        ),
        migrations.RemoveField(
            model_name="student",
            name="room_assets",
        ),
        migrations.RemoveField(
            model_name="student",
            name="room_number",
        ),
        migrations.RemoveField(
            model_name="student",
            name="room_type",
        ),
        migrations.AddField(
            model_name="room",
            name="Student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="master_app.student",
            ),
            preserve_default=False,
        ),
    ]
