# Generated by Django 5.0.1 on 2024-01-17 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_app", "0008_rename_student_room_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_number",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="room",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="master_app.student"
            ),
        ),
    ]
