# Generated by Django 5.0.1 on 2024-01-18 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_app", "0009_alter_room_room_number_alter_room_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="master_app.student",
            ),
        ),
    ]
