# Generated by Django 5.0.1 on 2024-01-10 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel_app", "0001_initial"),
        ("master_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_parent",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent",
                to="master_app.parent",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_student",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student",
                to="master_app.student",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_warden",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warden",
                to="master_app.warden",
            ),
        ),
    ]
