# Generated by Django 5.0.1 on 2024-01-12 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel_app", "0002_customuser_user_parent_customuser_user_student_and_more"),
        ("master_app", "0005_alter_hostelfees_hostel_alter_student_hostel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_parent",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="parent",
                to="master_app.parent",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_student",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="student",
                to="master_app.student",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_warden",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="warden",
                to="master_app.warden",
            ),
        ),
    ]
