# Generated by Django 5.0.1 on 2024-01-17 05:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("master_app", "0009_alter_room_room_number_alter_room_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("message_date", models.DateTimeField(auto_now_add=True)),
                (
                    "warden_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master_app.warden",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaintenanceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                ("request_reason", models.TextField()),
                ("reply", models.TextField(default=False)),
                ("reply_date", models.DateTimeField(default=False)),
                ("status", models.CharField(default="pending", max_length=10)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="master_app.student",
                    ),
                ),
                (
                    "warden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="master_app.warden",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OutPassRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_date", models.DateField(default=datetime.datetime.today)),
                ("to_date", models.DateField(default=datetime.datetime.today)),
                ("total_days", models.IntegerField()),
                ("reason", models.TextField()),
                ("rejected_reason", models.CharField(max_length=100)),
                ("status", models.CharField(default="pending", max_length=10)),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master_app.student",
                    ),
                ),
                (
                    "warden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="master_app.warden",
                    ),
                ),
            ],
        ),
    ]
