# Generated by Django 5.0.1 on 2024-01-17 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_app", "0009_alter_room_room_number_alter_room_student"),
        ("transaction_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcements",
            name="warden_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="master_app.warden",
            ),
        ),
    ]
