# Generated by Django 5.0.1 on 2024-01-17 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_app", "0009_alter_room_room_number_alter_room_student"),
        ("transaction_app", "0002_alter_announcements_warden_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcements",
            name="warden_id",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="master_app.warden",
            ),
            preserve_default=False,
        ),
    ]
