# Generated by Django 5.0.1 on 2024-01-17 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_app", "0009_alter_room_room_number_alter_room_student"),
        ("transaction_app", "0006_alter_announcements_warden_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outpassrequest",
            name="student_id",
        ),
        migrations.AddField(
            model_name="outpassrequest",
            name="student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                to="master_app.student",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="outpassrequest",
            name="from_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="outpassrequest",
            name="rejected_reason",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="outpassrequest",
            name="status",
            field=models.CharField(blank=True, default="pending", max_length=10),
        ),
        migrations.AlterField(
            model_name="outpassrequest",
            name="to_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="outpassrequest",
            name="total_days",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="outpassrequest",
            name="warden",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="master_app.warden",
            ),
        ),
    ]
