# Generated by Django 5.0.1 on 2024-01-18 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_app", "0009_alter_room_room_number_alter_room_student"),
        ("transaction_app", "0009_alter_outpassrequest_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenancerequest",
            name="reply",
            field=models.TextField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="maintenancerequest",
            name="reply_date",
            field=models.DateTimeField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="maintenancerequest",
            name="status",
            field=models.CharField(
                blank=True, default="pending", max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="maintenancerequest",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="master_app.student",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancerequest",
            name="warden",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="master_app.warden",
            ),
        ),
    ]
