# Generated by Django 5.0.1 on 2024-01-18 10:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transaction_app", "0010_alter_maintenancerequest_reply_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maintenancerequest",
            name="reply_date",
        ),
    ]
